task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/snapshot_exp/snapshot_f3c.yaml'

train_dataset:
    data_root: 'data/people_snapshot/citron2'
    human: 'citron2'
    ann_file: 'data/people_snapshot/citron2/params.npy'
    split: 'train'

test_dataset:
    data_root: 'data/people_snapshot/citron2'
    human: 'citron2'
    ann_file: 'data/people_snapshot/citron2/params.npy'
    split: 'test'

# data options
ratio: 1.
num_train_frame: 37
H: 717
W: 1276