task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/snapshot_exp/snapshot_f3c.yaml'

train_dataset:
    data_root: 'data/people_snapshot/jogging'
    human: 'jogging'
    ann_file: 'data/people_snapshot/jogging/params.npy'
    split: 'train'

test_dataset:
    data_root: 'data/people_snapshot/jogging'
    human: 'jogging'
    ann_file: 'data/people_snapshot/jogging/params.npy'
    split: 'test'

# data options
ratio: 1.
num_train_frame: 102
H: 718
W: 1278