task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/snapshot_exp/snapshot_f3c.yaml'

train_dataset:
    data_root: 'data/people_snapshot/seattle2'
    human: 'seattle2'
    ann_file: 'data/people_snapshot/seattle2/params.npy'
    split: 'train'

test_dataset:
    data_root: 'data/people_snapshot/seattle2'
    human: 'seattle2'
    ann_file: 'data/people_snapshot/seattle2/params.npy'
    split: 'test'

# data options
ratio: 1.
num_train_frame: 41
H: 708
W: 1259